### ISSUE TITLE
Simplify getContent(message) function

### ISSUE THREAD

**Issue by chris-mcdonald-dev** [chris-mcdonald-dev/korean-discord-app#31]
Our `getContent(message)` function that was introduced in PR #29 could be consolidated and removed.

``` js
const text = getContent(message).toLowerCase();
/* ....... lots of other unrelated code between these ....... */
function getContent(message) {
    return message.content ? message.content : "";
}
```

Perhaps it could be replaced with:
``` js
const text = (message.content ?? "test").toLowerCase();
```

There are some places where `.split()` is being used (expletives.js). We'll need to make sure we're not running it on an empty string. For these functions can use something like `if (!message.content) return` to fix this!
Feel free to try it out and we'll point it out in the PR review!

If someone could find where it is being used in the code-base, replace it with the concise version that would be ✨ _wonderful_. ✨

*You can use the search features in your code editor :*
![image](https://user-images.githubusercontent.com/69683963/112988676-19130000-9132-11eb-92bb-c9f56932d7af.png)

**Comment by well-balanced** [comment]
Can I work on this issue? kindly assign it to me!
